name: Daily Automated Commit

on:
  schedule:
    # Runs daily at 19:35 UTC (1:05 AM IST)
    - cron: '35 19 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update log file by 24f1000008@ds.study.iitm.ac.in
        run: |
          echo "Automated update at $(date)" >> daily_update.log

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_update.log
          git commit -m "Automated daily update: $(date)" || echo "No changes to commit"
          git push
